name: Executar Robô de Notícias

on:
  schedule:
    - cron: '0 9 * * *'
    - cron: '0 15 * * *'
    - cron: '0 21 * * *'
  workflow_dispatch:      

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar o Robô com Relatório
        env:
          WP_URL: ${{ secrets.WP_URL }}
          WP_USERNAME: ${{ secrets.WP_USERNAME }}
          WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          python bot/main.py 2>&1 | tee log_erro.txt
          
      - name: Guardar relatório se der erro
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-de-execucao
          path: log_erro.txt
